[mypy]
python_version = 3.12
strict = True
warn_unused_ignores = True
warn_redundant_casts = True
warn_return_any = True
show_error_codes = True
pretty = True

[mypy-beanie.*]
ignore_missing_imports = True

[mypy-motor.*]
ignore_missing_imports = True

[mypy-pymongo.*]
ignore_missing_imports = True

[mypy-mongomock_motor.*]
ignore_missing_imports = True

[mypy-tests.*]
disallow_untyped_defs = False
